version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: hiresense-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hiresense_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - hiresense-network


  redis:
    image: redis:7-alpine
    container_name: hiresense-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - hiresense-network


  backend:
    build:
      context: ./backend

    container_name: hiresense-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

    volumes:
      - ./backend:/app

    networks:
      - hiresense-network


volumes:

  postgres_data:
  redis_data:


networks:

  hiresense-network: