"""add user role active fields

Revision ID: 5d7432daa818
Revises: a8e87b98ed8a
Create Date: 2026-08-01 18:05:05.456750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7432daa818'
down_revision: Union[str, Sequence[str], None] = 'a8e87b98ed8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
#     op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
#     op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###
def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('users',sa.Column('role',sa.String(length=50),nullable=False,server_default='candidate'))

    op.add_column('users',sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.text('true')))

    op.add_column('users',sa.Column('updated_at',sa.DateTime(),nullable=False,server_default=sa.func.now()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
