"""add ai analysis fields to resume

Revision ID: 94045b91b255
Revises: ca36a4b034c4
Create Date: 2026-08-06 00:55:57.851855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94045b91b255'
down_revision: Union[str, Sequence[str], None] = 'ca36a4b034c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('analysis_result', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'analysis_result')
    op.drop_column('resumes', 'ats_score')
    # ### end Alembic commands ###
